stages:
  - build

job-build-all:
  stage: build
  image: reg.mikumikumi.xyz/base/kaniko-builder:latest
  script:
    - build

job-build-aliyun-directmail:
  stage: build
  image: reg.mikumikumi.xyz/base/kaniko-builder:latest
  variables:
    BUILD_DOCKERFILE: src/adapter/aliyun_directmail/Dockerfile
    BUILD_DESTINATION: reg.mikumikumi.xyz/cluster/smtp-external-relayer-by-aliyun-directmail:latest
  script:
    - build

job-build-microsoft-exchange-online:
  stage: build
  image: reg.mikumikumi.xyz/base/kaniko-builder:latest
  variables:
    BUILD_DOCKERFILE: src/adapter/microsoft_exchange_online/Dockerfile
    BUILD_DESTINATION: reg.mikumikumi.xyz/cluster/smtp-external-relayer-by-microsoft-exchange-online:latest
  script:
    - build
